FROM nginx:stable-alpine
WORKDIR /app
COPY ./backend/public /app/public
COPY ./docker/backend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/backend/nginx/nginx.conf /etc/nginx/nginx.conf
RUN chgrp -R nginx /tmp && chown -R nginx /tmp
USER nginx:nginx